Plonky2 bench
vacp2p/zk-explorations pull request #26
Opened 2024-02-15 22:56 UTC by tyshko-rostyslav

Changed to uniform benchmark representation

2024-02-16 14:43 UTC, jonesmarvin8 requested changes
Everything looks good. The README.md file either needs to be updated or removed.

2024-02-16 15:07 UTC, jonesmarvin8 approved these changes
Approved. No changes necessary.

2024-02-16 15:10 UTC, jonesmarvin8 requested changes
See comment above about README.md file.

2024-02-26 17:44 UTC, jonesmarvin8 commented on plonky2-bench/src/recursion.rs
> +use std::borrow::Borrow;
This does not appear to be used; tested  cargo bench without this line.

2024-02-26 17:44 UTC, jonesmarvin8 commented on plonky2-bench/src/recursion.rs
> +use plonky2::gates::gate::Gate;
This does not appear to be used; tested  cargo bench without this line.

2024-02-26 17:51 UTC, jonesmarvin8 submitted a review, later dismissed
Two class calls (as identified above) are not used.

Also, for aesthetics reasons, it could be nice to add `println!(" ");` in an appropriate spot to avoid the attached image 'issue.'
![Screenshot of Output](https://github.com/vacp2p/zk-explorations/assets/83104039/03e1a447-1608-4fb4-8c61-ad7f45c5bcb6)

2024-02-27 04:31 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +fn bench_recursive_snark(c: &mut Criterion) {
To match with other benchmarks like Arecibo and the two nova's, there probably should be a dedicated verify benchmark.

2024-02-28 11:06 UTC, tyshko-rostyslav commented on plonky2-bench/src/recursion.rs
> +use std::borrow::Borrow;
Removed

2024-02-28 11:06 UTC, tyshko-rostyslav commented on plonky2-bench/src/recursion.rs
> +use plonky2::gates::gate::Gate;
Removed

2024-02-29 03:34 UTC, jonesmarvin8 commented on plonky2-bench/src/recursion.rs
> +    let d = d - 1;
d is not used in the rest of this function.

2024-02-29 03:37 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +    common::common_data,
Line 17: `common::common_data` is not used.

2024-02-29 03:39 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +    recursion::{init, iterate_poseidon, recursion, C, D, F},
`recursion::recursion` is not used

2024-02-29 03:45 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +            init(d).unwrap();
In init(d), d is updated to `d = d-1`. However, this change only exists locally.

This update should be done here instead of in init(d).

2024-02-29 03:45 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +            init(d).unwrap();
Specifically, this is needed for line 140.

2024-02-29 03:48 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +                for _ in 0..d {
Should be d-1 as well.

2024-02-29 03:48 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +            init(d).unwrap();
In init(d), d is updated to `d = d-1`. This change is needed for this function on line 60.

2024-02-29 11:18 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +        let cyclic_circuit_data = builder.build::<C>();
Lines 42-58 probably should be part of the recursion.rs file as a new function. Perhaps, `pub fn init_witness()`?

2024-02-29 11:19 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +                for _ in 0..d {
Should the content of this loop be a function in recursion.rs?

2024-03-03 23:07 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +            init(d).unwrap();
Done

2024-03-03 23:08 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +                for _ in 0..d {
Moved d -1 as asked

2024-03-03 23:08 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +            init(d).unwrap();
Done

2024-03-03 23:09 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +    recursion::{init, iterate_poseidon, recursion, C, D, F},
removed

2024-03-03 23:09 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +    common::common_data,
removed

2024-03-03 23:10 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +    hash::{hash_types::HashOutTarget, poseidon::PoseidonHash},
removed

2024-03-03 23:10 UTC, tyshko-rostyslav commented on plonky2-bench/src/recursion.rs
> +    let d = d - 1;
removed

2024-03-03 23:22 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +                for _ in 0..d {
As of this loop, it's inside closure, that is actually  doing the benchmarking, so the answer is no

2024-03-03 23:31 UTC, tyshko-rostyslav commented on plonky2-bench/src/recursion.rs
> +pub fn init(
done

2024-03-03 23:32 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +        let initial_hash = &proof.public_inputs[..4];
done as `check_hash_value` function

2024-03-03 23:33 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +fn bench_recursive_snark_verify(c: &mut Criterion) {
Fixed accordingly

2024-03-03 23:39 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +        let cyclic_circuit_data = builder.build::<C>();
I don't think we should do it. There will not be any significant economy in codelines (since we are adding a lot of arguments to the function), as well as it will become even more difficult to read the code. At the same time there will not be more reusability, as we are calling these specific value only in benchmarks.

2024-03-03 23:59 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +                for _ in 0..d {
Noted.

2024-03-03 23:59 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +        let cyclic_circuit_data = builder.build::<C>();
Reasonable.

2024-03-04 00:02 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +        let d = d - 1;
This line should be moved to after line 33. This is because init(d) checks for d > 1. So, if cases include d = 2, this will result in an error.

2024-03-04 00:02 UTC, jonesmarvin8 commented on plonky2-bench/benches/poseidon.rs
> +        let d = d - 1;
Similar issue as above. Line 102 to after 105.

2024-03-04 00:05 UTC, jonesmarvin8 requested changes
Only minor placement issue that would cause issue if d = 2 was in the test cases.

2024-03-04 02:23 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +        let d = d - 1;
This line was removed from `init`, so no error will happen

2024-03-04 02:23 UTC, tyshko-rostyslav commented on plonky2-bench/benches/poseidon.rs
> +        let d = d - 1;
See https://github.com/vacp2p/zk-explorations/pull/26#discussion_r1510519787

2024-03-04 02:53 UTC, jonesmarvin8 approved these changes
Approved.

2024-03-04 09:08 UTC, merged