Halo2 shplonk  bench
vacp2p/zk-explorations pull request #28
Opened 2024-02-15 22:56 UTC by tyshko-rostyslav

Changed to uniform benchmark representation

2024-02-16 14:57 UTC, jonesmarvin8 approved these changes
Approved. No changes necessary.

2024-02-20 13:17 UTC, jonesmarvin8 requested changes

2024-02-20 13:17 UTC, jonesmarvin8 commented on halo2-shplonk/benches/poseidon.rs
> +        snark_verifier_sdk::halo2::gen_proof_gwc(
gen_proof_shplonk

2024-02-27 04:33 UTC, jonesmarvin8 commented on halo2-shplonk/benches/poseidon.rs
> +        snark_verifier_sdk::halo2::gen_proof_gwc(
Also: to match with other benchmarks like Arecibo and the two nova's, there probably should be a dedicated verify benchmark.

2024-02-28 11:07 UTC, tyshko-rostyslav commented on halo2-shplonk/benches/poseidon.rs
> +        snark_verifier_sdk::halo2::gen_proof_gwc(
Done

2024-03-04 03:00 UTC, jonesmarvin8 approved these changes
Approved.

2024-03-04 09:08 UTC, merged