Arecibo bench
vacp2p/zk-explorations pull request #29
Opened 2024-02-15 22:56 UTC by tyshko-rostyslav

Changed to uniform benchmark representation

2024-02-16 16:01 UTC, jonesmarvin8 requested changes

2024-02-16 16:01 UTC, jonesmarvin8 commented on arecibo/Cargo.toml
> +criterion = { version = "0.4", features = ["html_reports"] }
criterion = { version = "0.5", features = ["html_reports"] }

2024-02-25 22:41 UTC, tyshko-rostyslav commented on arecibo/Cargo.toml
> +criterion = { version = "0.4", features = ["html_reports"] }
fixed

2024-02-27 04:24 UTC, jonesmarvin8 approved these changes
Looks good.

2024-03-04 09:08 UTC, merged